name: Deploy - Build and push to Shared S. Account ECR
on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Release Number:'
        required: true
      environment:
        description: 'Image Tag (dev, qa, prod)'
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Set release number
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.G_TOKEN }}
      with:
        tag_name: ${{ github.events.inputs.release }}
        release_name: Release ${{ github.events.inputs.release }}
