name: Build Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Relase/Version to use in production"
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: LS Files
      id: lsversion
      run: echo "$(ls)"
    - name: Read VERSION file
      id: getversion
      run: echo "::set-output name=version::$(cat VERSION)"
    - name: Set release number
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.G_TOKEN }}
      with:
        tag_name: ${{ steps.getversion.outputs.version }}
        release_name: Release ${{ steps.getversion.outputs.version }}
  no-existe-error:
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
    - name: NO Hay Error
      if: failure()
      run: echo "NO SE ENCONTRO un Error"
  existe-error:
    runs-on: ubuntu-latest
    needs: [deploy]
    if: always() && needs.deploy.result == 'failure'
    steps:
    - name: Si Hay Error
      run: echo "Existe un Error - ${{ github.event.inputs.version }}"
