name: CI-CD Calls
on:
  workflow_run:
    workflows: [Build Release]
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The triggering workflow passed'
      - run: echo "VERSION - ${{ github.event.inputs.version }}"
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'
      - name: Prueba
        uses: actions/github-script@v6
        with:
          script: |
            echo "${{ toJson(context) }}"
